#!/usr/bin/env bash
chrome=/Applications/"Google Chrome.app"/Contents/MacOS/"Google Chrome"
user_dir=~/Documents/dev_chrome
"$chrome" --user-data-dir=$user_dir --no-default-browser-check --disable-web-security \
--no-first-run --disable-default-apps --disable-popup-blocking --disable-translate \
--disable-background-timer-throttling --disable-device-discovery-notifications